CREATE OR ALTER PROCEDURE GET_BOOKS_SORT_AUTHOR
AS 
BEGIN	
	SET NOCOUNT ON

		SELECT B.BOOKID,
				B.PUBLISHER,
				B.TITLE,
				B.AUTHORFIRSTNAME,
				B.AUTHORLASTNAME,
				CONCAT (AUTHORLASTNAME,' ',AUTHORFIRSTNAME) AS 'AUTHORNAME',		
				PRICE
		FROM BOOKS AS B 
		ORDER BY AUTHORNAME,TITLE

	SET NOCOUNT OFF
END