CREATE PROCEDURE INSERT_BOOKS(
    @BOOKS BOOK_TABLE_TYPE READONLY)
AS
BEGIN
    INSERT INTO BOOKS
				(PUBLISHER,
				TITLE,
				AUTHORLASTNAME,
				AUTHORFIRSTNAME,
				PRICE)
				SELECT
				PUBLISHER,
				TITLE,
				AUTHORLASTNAME,
				AUTHORFIRSTNAME,
				PRICE 
				FROM @BOOKS;
END;